# Generated by Django 5.2.6 on 2025-09-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_and_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('location', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('appreciation_mark', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='services_and_projects.service')),
            ],
        ),
    ]
