# Generated by Django 5.2.6 on 2025-11-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_and_projects', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
