# Generated by Django 5.2.6 on 2026-07-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('regular', 'Quote Requests'), ('container', 'Container Conversion Quotes')], max_length=20)),
                ('quote_id', models.PositiveIntegerField()),
                ('first_exported_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'quote_id'), name='uniq_exported_quote')],
            },
        ),
    ]
