# Generated by Django 5.2.6 on 2026-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_sheet', '0002_sync_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportedquote',
            name='kind',
            field=models.CharField(choices=[('regular', 'Website Quote Requests'), ('solar', 'Website Solar Quote Requests'), ('container', 'Website Container Conversion Quotes')], max_length=20),
        ),
    ]
