# Generated by Django 5.2.6 on 2026-06-16 09:06

import apps.weight_scale.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Stable hardware identifier, e.g. the ESP32 MAC address.', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(db_index=True, default=apps.weight_scale.models.generate_api_key, help_text='Secret key the device sends in the X-API-Key header.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='WeightReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds')], default='kg', max_length=4)),
                ('raw_value', models.IntegerField(blank=True, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weight_scale.scaledevice')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', '-received_at'], name='weight_scal_device__ef5a28_idx')],
            },
        ),
    ]
