# Generated by Django 5.2.6 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_scale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaledevice',
            name='device_id',
            field=models.CharField(blank=True, help_text='Stable hardware identifier, e.g. the ESP32 MAC address.', max_length=64, null=True, unique=True),
        ),
    ]
