# Generated by Django 5.2.6 on 2026-09-24 18:39

import apps.client_portal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to block every contact at this company from signing in.')),
                ('notes', models.TextField(blank=True, help_text='Internal only — never shown to the client.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client company',
                'verbose_name_plural': 'Client companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='The address login codes are sent to.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text="Untick to revoke this person's access.")),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='client_portal.clientcompany')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Retired sites drop out of the new-ticket form but old tickets keep them.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='client_portal.clientcompany')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login code',
                'verbose_name_plural': 'Login codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'consumed'], name='client_port_email_b70c54_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service', models.CharField(choices=[('electrical', 'Electrical'), ('solar', 'Solar'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('waterproofing', 'Waterproofing and roofing'), ('maintenance', 'Maintenance')], max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('visit_booked', 'Visit booked'), ('on_site', 'On site'), ('in_progress', 'In progress'), ('quote_to_approve', 'Quote to approve'), ('info_needed', 'Info needed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('preferred_visit_date', models.DateField(blank=True, null=True)),
                ('site_contact_name', models.CharField(blank=True, max_length=150)),
                ('site_contact_phone', models.CharField(blank=True, max_length=30)),
                ('technician_name', models.CharField(blank=True, help_text='Shown to the client. Leave blank until someone is assigned.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='client_portal.clientcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='client_portal.clientcontact')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='client_portal.clientsite')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.client_portal.models._attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='client_portal.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientsite',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_client_site_per_company'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'status'], name='client_port_company_d10480_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', '-updated_at'], name='client_port_company_5a4aa1_idx'),
        ),
    ]
