# Generated by Django 5.2.6 on 2026-09-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsite',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The portal contact who added it. Blank when APS added it in admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_added', to='client_portal.clientcontact'),
        ),
    ]
