# Generated by Django 5.2.6 on 2026-09-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0002_clientsite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='session_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
