# Generated by Django 5.2.6 on 2026-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0007_ticket_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_emailed_upto',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='staff_emailed_upto',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
