# Generated by Django 5.2.6 on 2025-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='appreciation_mark',
            field=models.IntegerField(default=0),
        ),
    ]
