# Generated by Django 5.2.6 on 2026-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modular_size', models.CharField(choices=[('3m', '3 Meter'), ('6m', '6 Meter (20ft Container)'), ('12m', '12 Meter (40ft Container)'), ('9m_parkhome', '9 Meter Parkhome'), ('conversion_only', 'Conversion Only (Client-Owned Container)')], help_text='Primary container or modular unit size', max_length=20)),
                ('domeshelter_size', models.CharField(blank=True, choices=[('none', 'No Dome Shelter'), ('6x6', '6m x 6m'), ('12x12', '12m x 12m'), ('18x18', '18m x 18m')], default='none', max_length=10)),
                ('rent_or_buy', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=10)),
                ('rent_furniture', models.BooleanField(default=False)),
                ('flatpack', models.BooleanField(default=False, help_text='Delivered unassembled and assembled on site')),
                ('refrigeration_type', models.CharField(choices=[('none', 'Not Required'), ('single_phase', 'Single-Phase'), ('three_phase', 'Three-Phase')], default='none', max_length=20)),
                ('transport_or_export_address', models.TextField(help_text='Delivery address or export destination')),
                ('is_processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
