# Generated by Django 5.2.6 on 2026-02-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteRequest',
            new_name='ServiceRequest',
        ),
    ]
