# Generated by Django 5.2.6 on 2026-02-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0002_rename_quoterequest_servicerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ablution',
            field=models.BooleanField(default=False, help_text='Include toilet / washroom unit'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_contact_method',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='call', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional for individual clients', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='domeshelter_size',
            field=models.CharField(choices=[('none', 'No Dome Shelter'), ('6x6', '6m x 6m'), ('12x12', '12m x 12m'), ('18x18', '18m x 18m')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='flatpack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='modular_size',
            field=models.CharField(choices=[('3m', '3 Meter'), ('6m', '6 Meter (20ft Container)'), ('12m', '12 Meter (40ft Container)'), ('9m_parkhome', '9 Meter Parkhome'), ('conversion_only', 'Conversion Only (Client-Owned Container)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='transport_or_export_address',
            field=models.TextField(),
        ),
    ]
