# Generated by Django 5.2.6 on 2026-02-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0003_alter_servicerequest_options_servicerequest_ablution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
