# Generated by Django 5.2.6 on 2026-02-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0004_alter_servicerequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='intended_use',
            field=models.CharField(blank=True, choices=[('storage', 'Storage'), ('office', 'Office'), ('ablution', 'Ablution'), ('accommodation', 'Accommodation'), ('school', 'School'), ('conversion', 'Conversion')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('container', 'Container'), ('parkhome', 'Parkhome')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='flatpack',
            field=models.BooleanField(default=False, help_text='Delivered unassembled & assembled on-site'),
        ),
    ]
