# Generated by Django 5.2.6 on 2026-02-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0005_servicerequest_intended_use_servicerequest_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='intended_use',
            field=models.CharField(choices=[('storage', 'Storage'), ('office', 'Office'), ('ablution', 'Ablution'), ('accommodation', 'Accommodation'), ('school', 'School'), ('conversion', 'Conversion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='unit_type',
            field=models.CharField(choices=[('container', 'Container'), ('parkhome', 'Parkhome')], max_length=10),
        ),
    ]
