# Generated by Django 5.2.6 on 2026-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0006_alter_servicerequest_intended_use_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='ablution',
            new_name='ablution_included',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='intended_use',
            field=models.CharField(choices=[('storage', 'Storage'), ('office', 'Office'), ('accommodation', 'Accommodation'), ('school', 'School'), ('conversion', 'Conversion')], max_length=20),
        ),
    ]
