# Generated by Django 5.2.6 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0007_rename_ablution_servicerequest_ablution_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ablution_included',
            field=models.BooleanField(default=False, help_text='Included toilet / washroom unit'),
        ),
    ]
