# Generated by Django 5.2.6 on 2026-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0008_servicerequest_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Any additional requirements or special requests'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='intended_use',
            field=models.CharField(choices=[('storage', 'Storage'), ('office', 'Office'), ('accommodation', 'Accommodation'), ('school', 'School'), ('custom_conversion', 'Custom Conversion')], max_length=20),
        ),
    ]
