# Generated by Django 5.2.6 on 2026-02-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0009_alter_servicerequest_additional_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='ablution_included',
            new_name='ablution_unit',
        ),
    ]
