# Generated by Django 5.2.6 on 2026-04-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0010_rename_ablution_included_servicerequest_ablution_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='air_conditioning',
            field=models.BooleanField(default=False, help_text='Supply and installation of air conditioning'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='budget_range',
            field=models.CharField(choices=[('100_to_250k', 'R100,000 – R250,000'), ('250_to_500k', 'R250,000 – R500,000'), ('500k_to_1m', 'R500,000 – R1,000,000'), ('over_1m', 'Over R1,000,000'), ('not_sure', 'Not Sure Yet')], default='not_sure', help_text="Client's budget range", max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='custom_painting_branding',
            field=models.BooleanField(default=False, help_text='Custom exterior paint colours or branded finishes'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_and_installation',
            field=models.BooleanField(default=False, help_text='Transport, offloading, positioning, and installation on site'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='electrical_installation',
            field=models.BooleanField(default=False, help_text='Internal wiring, plugs, lights, and DB board installation'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='finish_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('mid_range', 'Mid-Range'), ('premium', 'Premium'), ('to_be_discussed', 'To Be Discussed')], default='standard', help_text='Desired finish level / fittings preference', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='insulation',
            field=models.BooleanField(default=False, help_text='Thermal insulation for improved temperature control'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='interior_finishes',
            field=models.BooleanField(default=False, help_text='Internal cladding, ceilings, flooring, and finish upgrades'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='plumbing_installation',
            field=models.BooleanField(default=False, help_text='Water supply and drainage points where required'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='project_timeframe',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('within_1_month', 'Within 1 Month'), ('1_to_3_months', '1–3 Months'), ('budgeting_only', 'Budgeting Only')], help_text="Client's project timeline", max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='solar_backup_power',
            field=models.BooleanField(default=False, help_text='Solar, inverter, and battery backup solutions'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ablution_unit',
            field=models.BooleanField(default=False, help_text='Include toilet / washroom facilities'),
        ),
    ]
