# Generated by Django 5.2.6 on 2026-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0011_servicerequest_air_conditioning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='domeshelter_size',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='flatpack',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='refrigeration_type',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='rent_furniture',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='rent_or_buy',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='intended_use',
            field=models.CharField(choices=[('storage', 'Storage'), ('office', 'Office'), ('accommodation', 'Accommodation'), ('classroom_or_school', 'Classroom / School'), ('site_office', 'Site Office'), ('ablution', 'Ablution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='modular_size',
            field=models.CharField(choices=[('6m', '6 Meter (20ft Container)'), ('12m', '12 Meter (40ft Container)'), ('client_supplied_container', 'Client-Supplied Container')], max_length=25),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='unit_type',
            field=models.CharField(choices=[('container', 'Container'), ('conversion_only', 'Conversion Only (Client-Supplied Container)')], max_length=20),
        ),
    ]
