# Generated by Django 5.2.6 on 2026-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_conversion', '0012_remove_servicerequest_domeshelter_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('image', models.ImageField(upload_to='container_projects/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='container_projects/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='container_projects/')),
                ('location', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('appreciation_mark', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Container Project',
                'verbose_name_plural': 'Container Projects',
            },
        ),
    ]
