# Generated by Django 5.2.6 on 2026-05-08 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('report_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('site_name', models.CharField(max_length=200)),
                ('has_battery', models.BooleanField(default=False)),
                ('solar_yield', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('battery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usable_solar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_saving', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_from_battery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_to_grid_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell_to_grid_r', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grid_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='solar_dashboard.solarreport')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
