# Generated by Django 5.2.6 on 2026-09-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_dashboard', '0005_remove_sitedata_has_battery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who added it: the client, or blank/staff when APS added it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
