"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'alter-power.co.za', 
    'www.alter-power.co.za', 
    'deb8b3b7582e.ngrok-free.app', 
    'localhost:5173', 
    'localhost:8000', 
    '127.0.0.1:8000', 
    'localhost', 
    '127.0.0.1', 
    '31.97.114.215',
    '0.0.0.0',
    'srv934843.hstgr.cloud',
    'autoconfig.srv934843.hstgr.cloud',
    'mail.srv934843.hstgr.cloud'
]

CORS_ALLOW_ALL_ORIGINS = False  # Set to True in Development/Testing, False in Production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",

    # '31.97.114.215',
    # '31.97.114.215:8000',
    # '31.97.114.215:3000',
    'http://31.97.114.215',
    'http://31.97.114.215:8000',
    'http://31.97.114.215:3000',
    'https://31.97.114.215',
    'https://31.97.114.215:8000',
    'https://31.97.114.215:3000',
    # 'alter-power.co.za',
    'http://alter-power.co.za',
    'https://alter-power.co.za',
    # 'www.alter-power.co.za',
    'http://www.alter-power.co.za',
    'https://www.alter-power.co.za',
    # 'alter-power.co.za:3000',
    'http://alter-power.co.za:3000',
    'https://alter-power.co.za:3000',
    # 'www.alter-power.co.za:3000',
    'http://www.alter-power.co.za:3000',
    'https://www.alter-power.co.za:3000',
    # 'alter-power.co.za:8000',
    'http://alter-power.co.za:8000',
    'https://alter-power.co.za:8000',
    # 'www.alter-power.co.za:8000',
    'http://www.alter-power.co.za:8000',
    'https://www.alter-power.co.za:8000',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://31.97.114.215',
    'http://31.97.114.215:8000',
    'http://31.97.114.215:3000',
    'https://31.97.114.215',
    'https://31.97.114.215:8000',
    'https://31.97.114.215:3000',
    'http://alter-power.co.za',
    'https://alter-power.co.za',
    'http://www.alter-power.co.za',
    'https://www.alter-power.co.za',
    'http://alter-power.co.za:3000',
    'https://alter-power.co.za:3000',
    'http://www.alter-power.co.za:3000',
    'https://www.alter-power.co.za:3000',
    'http://alter-power.co.za:8000',
    'https://alter-power.co.za:8000',
    'http://www.alter-power.co.za:8000',
    'https://www.alter-power.co.za:8000',
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Jazzmin should be at the top to override default admin templates
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party packages
    'corsheaders',
    'rest_framework',
    # NOTE: Don't create public API Documentation. Create a private custom API Documentation.
    # 'drf_yasg',

    # Custom apps
    'apps.blog',
    'apps.chatbot',
    'apps.container_conversion',
    'apps.core',
    'apps.quote_request',
    'apps.request_solar_cleaning',
    'apps.subscription',
    'apps.services_and_projects',
    'apps.solar_dashboard',
    'apps.weight_scale',

    # Celery Beat for periodic tasks (at last to avoid circular imports with tasks)
    'django_celery_beat',
]

# Authenticate by username case-insensitively (client requirement: "urban" == "Urban").
# Keep the default backend as a fallback for the admin/session login path.
AUTHENTICATION_BACKENDS = [
    'apps.core.backends.CaseInsensitiveModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_ROOT = "/home/backend/staticfiles"

# For additional static file directories (optional)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # your custom static folder during development
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SECURE_SSL_REDIRECT = False  # Nginx handles redirects
SESSION_COOKIE_SECURE = True  # Cookies over HTTPS
CSRF_COOKIE_SECURE = True  # CSRF cookies over HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "utils.exceptions.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


# NOTE: Don't create public API Documentation. Create a private custom API Documentation.
# SWAGGER_SETTINGS = {
#     'USE_SESSION_AUTH': False,
#     'JSON_EDITOR': True,
# }


LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] [{asctime}] [{module}] [{pathname}] [{lineno}] >> {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] >> {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'prod.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,  # Keep 5 backup/old-log files
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {  # Root logger
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.blog': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.chatbot': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.quote_request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.request_solar_cleaning': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.subscription': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.services_and_projects': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.solar_dashboard': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "APS Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "APS Admin",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "APS Admin",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "logo.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to APS Admin",

    # Copyright on the footer
    "copyright": "Alternate Power Solutions",

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "blog.BlogCategory": "fas fa-folder",
        "blog.Blog": "fas fa-newspaper",

        "container_conversion.ServiceRequest": "fas fa-shipping-fast",

        "quote_request.QuoteRequest": "fas fa-envelope-open-text",

        "request_solar_cleaning.Client": "fas fa-user-friends",
        "request_solar_cleaning.Subscription": "fas fa-screwdriver-wrench",

        "services_and_projects.Service": "fas fa-cogs",
        "services_and_projects.Project": "fas fa-project-diagram",

        "subscription.Client": "fas fa-user-friends",
        "subscription.Subscription": "fas fa-desktop",
    },
}


# Email Service Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_RECIPIENT = os.getenv('EMAIL_RECIPIENT')


# ====================== CELERY ======================
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Johannesburg'   # ← Client timezone
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# AI Chatbot configurations (Grok)
CHATBOT_API_KEY = os.getenv("CHATBOT_API_KEY")
CHATBOT_API_URL = os.getenv("CHATBOT_API_URL")


# PayFast Configuration
# PAYFAST_SANDBOX = os.getenv('PAYFAST_SANDBOX', False)  # Set to True in Development/Testing, False in Production
PAYFAST_SANDBOX = False  # Set to True in Development/Testing, False in Production
PAYFAST_MERCHANT_ID = os.getenv('PAYFAST_MERCHANT_ID')
PAYFAST_MERCHANT_KEY = os.getenv('PAYFAST_MERCHANT_KEY')
PAYFAST_PASSPHRASE = os.getenv('PAYFAST_PASSPHRASE')

# PayFast URLs - Update these based on your domain
PAYFAST_RETURN_URL = os.getenv('PAYFAST_RETURN_URL')
PAYFAST_CANCEL_URL = os.getenv('PAYFAST_CANCEL_URL')
PAYFAST_NOTIFY_URL = os.getenv('PAYFAST_NOTIFY_URL')  # Must be publicly accessible. PayFast needs to be able to reach this URL to send payment notifications.
PAYFAST_SOLAR_CLEANING_NOTIFY_URL = os.getenv('PAYFAST_SOLAR_CLEANING_NOTIFY_URL')  # Must be publicly accessible. PayFast needs to be able to reach this URL to send payment notifications.
