# Generated by Django 5.2.6 on 2026-08-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monitoring', 'Monitoring (R99/mo)'), ('cylinder_swap', 'Cylinder swap add-on (R199/mo)')], max_length=20)),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf_payment_id', models.CharField(max_length=255, unique=True)),
                ('m_payment_id', models.CharField(blank=True, max_length=255)),
                ('payfast_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payfast_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payfast_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('subscription_length', models.IntegerField(default=0)),
                ('swap_addon_active', models.BooleanField(default=False)),
                ('swap_addon_token', models.CharField(blank=True, max_length=255, null=True)),
                ('swap_addon_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('swap_addon_length', models.IntegerField(default=0)),
                ('swap_addon_last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
