# Generated by Django 5.2.6 on 2026-08-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gg_subscription', '0001_initial'),
        ('gg_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gg_users.gasguarduser'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='gg_users.gasguarduser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gg_subscription.subscription'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'plan'], name='gg_subscrip_user_id_716cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['pf_payment_id'], name='gg_subscrip_pf_paym_b20a38_idx'),
        ),
    ]
