# Generated by Django 5.2.6 on 2026-09-22 12:09

import django.db.models.deletion
from django.db import migrations, models


def attach_existing_to_first_device(apps, schema_editor):
    """
    Point pre-existing account-wide subscriptions at a site.

    Before this migration a subscription belonged to a user, not a site. Attach
    each one to that user's first device so no billing history is orphaned. A
    user with no devices keeps a device-less row, which the API treats as
    inactive and admin can clean up.
    """
    Subscription = apps.get_model('gg_subscription', 'Subscription')
    ScaleDevice = apps.get_model('gg_weight_scale', 'ScaleDevice')
    for sub in Subscription.objects.filter(device__isnull=True):
        device = (
            ScaleDevice.objects.filter(owner_id=sub.user_id)
            .order_by('id')
            .first()
        )
        if device is not None:
            sub.device_id = device.id
            sub.save(update_fields=['device'])


def noop_reverse(apps, schema_editor):
    """Reversing just drops the column; nothing to undo here."""


class Migration(migrations.Migration):

    dependencies = [
        ('gg_subscription', '0002_initial'),
        ('gg_users', '0001_initial'),
        ('gg_weight_scale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['device__name', 'device__device_id']},
        ),
        migrations.AddField(
            model_name='subscription',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gg_weight_scale.scaledevice'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gg_users.gasguarduser'),
        ),
        migrations.RunPython(attach_existing_to_first_device, noop_reverse),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device',), name='uniq_subscription_per_device'),
        ),
    ]
