# Generated by Django 5.2.6 on 2025-12-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_solar_cleaning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Subscription',
        ),
    ]
