# Generated by Django 5.2.6 on 2025-12-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_solar_cleaning', '0002_rename_request_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='paid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='installed_panels_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='inverter_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='inverter_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_length',
            field=models.IntegerField(default=0),
        ),
    ]
