# Generated by Django 5.2.6 on 2026-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_message', models.TextField(blank=True, default='')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_recovered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
