# Generated by Django 5.2.6 on 2026-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_detection', '0002_soc_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertstate',
            name='consecutive_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
