# Generated by Django 5.2.6 on 2026-07-12 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_detection', '0004_behaviour_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('soc_imbalance', 'SOC Imbalance'), ('charge_behaviour', 'Charge Behaviour')], max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_by', models.CharField(blank=True, default='', max_length=120)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
