# Generated by Django 5.2.6 on 2026-08-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gg_alerts', '0001_initial'),
        ('gg_weight_scale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowgasalertstate',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_gas_alert_state', to='gg_weight_scale.scaledevice'),
        ),
    ]
