# Generated by Django 5.2.6 on 2026-07-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('drive_modified_time', models.CharField(blank=True, default='', max_length=64)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('text', models.TextField(blank=True, default='')),
                ('chat_name', models.CharField(blank=True, default='', max_length=512)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('marked_as_job', models.BooleanField(db_index=True, default=False)),
                ('marked_as_job_at', models.DateTimeField(blank=True, null=True)),
                ('exported_to_jobs_sheet', models.BooleanField(db_index=True, default=False)),
                ('exported_to_jobs_sheet_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_import.importedfile')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['marked_as_job', 'exported_to_jobs_sheet'], name='whatsapp_im_marked__98530a_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'sent_at', 'text'), name='uniq_whatsapp_message')],
            },
        ),
    ]
