# Generated by Django 5.2.6 on 2026-07-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_import', '0003_jobs_export_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='dismissed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
