# Generated by Django 5.2.6 on 2025-09-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_request', '0001_initial'),
        ('services_and_projects', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='services_and_projects.service'),
        ),
    ]
