# Generated by Django 5.2.6 on 2026-02-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_request', '0003_alter_quoterequest_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'verbose_name_plural': 'Quote Requests'},
        ),
    ]
