# Generated by Django 5.2.6 on 2026-04-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_request', '0004_alter_quoterequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarQuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural')], max_length=20, null=True)),
                ('suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, choices=[('western_cape', 'Western Cape'), ('gauteng', 'Gauteng'), ('kwazulu_natal', 'KwaZulu-Natal'), ('eastern_cape', 'Eastern Cape'), ('limpopo', 'Limpopo'), ('mpumalanga', 'Mpumalanga'), ('free_state', 'Free State'), ('north_west', 'North West'), ('northern_cape', 'Northern Cape')], max_length=30, null=True)),
                ('roof_type', models.CharField(blank=True, choices=[('ibr_corrugated', 'IBR / corrugated iron'), ('concrete_flat', 'Concrete slab / flat roof'), ('tiled', 'Tiled'), ('klip_lok', 'Klip-Lok'), ('asbestos', 'Asbestos'), ('other', 'Other')], max_length=30, null=True)),
                ('monthly_bill', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_goal', models.CharField(blank=True, choices=[('backup', 'Backup power'), ('savings', 'Save on bills'), ('offgrid', 'Go off-grid'), ('all', 'All of the above')], max_length=20, null=True)),
                ('grid_connection', models.CharField(blank=True, choices=[('single_phase_eskom', 'Single phase (Eskom direct)'), ('three_phase_eskom', 'Three phase (Eskom direct)'), ('prepaid_meter', 'Prepaid meter'), ('municipality_metered', 'Municipality metered'), ('no_connection', 'No current connection')], max_length=30, null=True)),
                ('budget_range', models.CharField(blank=True, choices=[('under50k', 'Under R50k'), ('50-150k', 'R50k - R150k'), ('150-300k', 'R150k - R300k'), ('over300k', 'Over R300k')], max_length=20, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('asap', 'ASAP - within 1 month'), ('1_to_3_months', '1-3 months'), ('3_to_6_months', '3-6 months'), ('exploring', 'Just exploring options')], max_length=20, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, choices=[('referral', 'Referral / word of mouth'), ('google', 'Google search'), ('social_media', 'Facebook / Instagram'), ('existing_client', 'Existing APS client'), ('other', 'Other')], max_length=20, null=True)),
                ('quote_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_details', to='quote_request.quoterequest')),
            ],
            options={
                'verbose_name_plural': 'Solar Quote Details',
            },
        ),
    ]
