# Generated by Django 5.2.6 on 2026-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_request', '0005_solarquotedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarquotedetails',
            name='company',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
