# Generated by Django 5.2.6 on 2026-08-13 09:34

import apps.gas_guard.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasGuardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('tier', models.CharField(choices=[('device', 'Device only'), ('subscribed', 'Subscribed')], default='device', max_length=12)),
                ('email_alerts_enabled', models.BooleanField(default=False)),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this Gas Guard user belongs to.', related_name='gas_guard_users', related_query_name='gas_guard_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this Gas Guard user.', related_name='gas_guard_users', related_query_name='gas_guard_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Gas Guard user',
                'verbose_name_plural': 'Gas Guard users',
            },
            managers=[
                ('objects', apps.gas_guard.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('verification_code', models.CharField(max_length=6)),
                ('verification_code_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'indexes': [models.Index(fields=['email'], name='gg_users_pe_email_08680d_idx'), models.Index(fields=['verification_code'], name='gg_users_pe_verific_851f38_idx')],
            },
        ),
    ]
