# Generated by Django 5.2.6 on 2026-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('forgot', 'Forgot password'), ('change', 'Change password')], default='forgot', max_length=8)),
                ('new_password', models.CharField(max_length=128)),
                ('verification_code', models.CharField(max_length=6)),
                ('verification_code_expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password Reset Code',
                'verbose_name_plural': 'Password Reset Codes',
                'indexes': [models.Index(fields=['email'], name='gg_users_pa_email_40613f_idx'), models.Index(fields=['verification_code'], name='gg_users_pa_verific_f3a946_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'purpose'), name='uniq_pending_reset_per_email_purpose')],
            },
        ),
    ]
