# Generated by Django 5.2.6 on 2026-08-13 09:34

import apps.gas_guard.weight_scale.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gg_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text='Stable hardware identifier, e.g. the ESP32 MAC address.', max_length=64, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tare_kg', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Weight of the empty cylinder in kg.', max_digits=6)),
                ('full_gas_kg', models.DecimalField(decimal_places=2, default=Decimal('48.00'), help_text='Weight of the gas alone when the cylinder is full, in kg.', max_digits=6)),
                ('api_key', models.CharField(db_index=True, default=apps.gas_guard.weight_scale.models.generate_api_key, help_text='Secret key the device sends in the X-API-Key header.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gg_users.gasguarduser')),
            ],
            options={
                'ordering': ['name', 'device_id'],
            },
        ),
        migrations.CreateModel(
            name='WeightReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds')], default='kg', max_length=4)),
                ('raw_value', models.IntegerField(blank=True, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rssi_dbm', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='gg_weight_scale.scaledevice')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', '-received_at'], name='gg_weight_s_device__233a16_idx')],
            },
        ),
    ]
