# Generated by Django 5.2.6 on 2026-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(choices=[('monitoring', 'Inverter & Battery Monitoring Plan'), ('maintenance', 'Solar & Inverter Maintenance Plan')], max_length=20)),
                ('subscription_id', models.PositiveIntegerField()),
                ('first_exported_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('app_label', 'subscription_id'), name='uniq_exported_subscription')],
            },
        ),
    ]
