# Generated by Django 5.2.6 on 2025-09-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_client_address_alter_subscription_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
