# Generated by Django 5.2.6 on 2025-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
