# Generated by Django 5.2.6 on 2025-10-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_customer_id',
            new_name='payfast_payment_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='payfast_token',
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscription.client'),
        ),
    ]
