# Generated by Django 5.2.6 on 2025-10-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_rename_stripe_customer_id_subscription_payfast_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='inverter_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
