# Generated by Django 5.2.6 on 2026-08-31 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscription_inverter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pf_payment_id', models.CharField(max_length=255, unique=True)),
                ('m_payment_id', models.CharField(blank=True, max_length=255)),
                ('payfast_token', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscription.client')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscription.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription'], name='subscriptio_subscri_fbac44_idx'), models.Index(fields=['pf_payment_id'], name='subscriptio_pf_paym_f51815_idx')],
            },
        ),
    ]
